version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers

commands:
  yarn_install:
    description: 'Install Dependencies'
    steps:
      - run: yarn install --frozen-lockfile --non-interactive
      - save_cache:
          key: nrwl-cache-node12-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  restore_yarn_cache:
    description: 'Restore Cached Dependencies'
    steps:
      - restore_cache:
          keys:
            - nrwl-cache-node12-{{ checksum "yarn.lock" }}
            - nrwl-cache-node12-
  setup:
    description: 'Setup Executor'
    steps:
      - checkout
      - restore_yarn_cache
      - yarn_install

jobs:
  build-master:
    executor: default
    steps:
      - setup
      - run: yarn nx affected --target=lint --base=origin/master~1 --parallel
      - run: yarn nx affected --target=test --base=origin/master~1
      - run: yarn nx affected --target=build --base=origin/master~1 --prod
  build-pr:
    executor: default
    steps:
      - setup
      - run: yarn nx affected --target=lint --base=origin/master --parallel
      - run: yarn nx affected --target=test --base=origin/master
      - run: yarn nx affected --target=build --base=origin/master --prod

workflows:
  version: 2.1
  default_workflow:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
      - build-pr:
          filters:
            branches:
              ignore:
                - master
